# Site settings
title: 我的博客
SEOTitle: 我的博客 | My Blog
header-img: img/post-bg-desk.jpg
email: 暂无
description: "写一句你想写的话"
keyword: "我的博客"
url: "http://name.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/name/name.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "这里写自我介绍"
sidebar-avatar: /img/avatar_binggan.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     暂无
#zhihu_username:     暂无 #最后会渲染成https://www.zhihu.com/people/%E6%9A%82%E6%97%A0
#github_username:    暂无 #最后会渲染成https://github.com/%E6%9A%82%E6%97%A0
#facebook_username:  暂无 #最后会渲染成https://www.facebook.com/%E6%9A%82%E6%97%A0
#jianshu_username:   暂无 #最后会渲染成https://www.jianshu.com/u/%E6%9A%82%E6%97%A00
#twitter_username:   暂无




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]
plugins: [jekyll-paginate]



# Markdown settings
markdown: kramdown # markdown解析器
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID:                             #生成的clientID
  clientSecret:     #生成的clientSecret
  repo: name.github.io    #仓库名称
  owner:     #github用户名
  admin: 
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 
# Google Analytics
ga_track_id:             # Format: UA-xxxxxx-xx
ga_domain:                # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
    #{
       # title: "Apple",
       # href: "https://apple.com"
    #},{
      #  title: "Apple Developer",
       # href: "https://developer.apple.com/"
    #}
#]
